[cisco-sso/kibana] Add config file for kibana
cisco-sso/charts pull request #7
Opened 2018-05-28 16:38 UTC by rustycl0ck

* Allow properties to be provided directly in the config file instead of
  through environment variables. This is useful when there are dots as
  well as underscores in the property name.
* Fix broken ingress
* Add verbosity during plugin installation to keep track of specific
  plugin failures

2018-05-29 22:15 UTC, ghost requested changes
Need to understand what's going on here.

- Chart version is not advanced by this PR.
- ~~No upstream PR is linked.~~
- Chart is not new to this repo, so we may need a rebase (or delete-recreate) of `src/kibana` to base on latest upstream.  Right now the result would be ambiguous in comparison to upstream without careful inspection.

2018-05-29 22:15 UTC, josdotso commented on pkg/index.yaml
> +    - https://raw.githubusercontent.com/cisco-sso/k8s-charts/master/pkg/kafka-schema-registry-0.2.0.tgz
^ This will probably break the repo. Please align with the old index on URL stuff.

2018-06-15 15:10 UTC, josdotso commented on src/kibana/templates/deployment.yaml
> +              mountPath: "/usr/share/kibana/config/kibana.yml"
Please see my comments on the upstream PR WRT exposing the entire config at values.yaml

2018-07-17 15:56 UTC, rustycl0ck commented
@josdotso @rtluckie This is ready for review.

2018-07-19 20:25 UTC, ghost commented
@rustycl0ck, would you be willing to change `configFiles` to `files` and re-run awake?

2018-07-20 07:08 UTC, rustycl0ck commented
Fixed!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On July 20, 2018 1:55 AM, Joshua Dotson <notifications@github.com> wrote:

> [@rustycl0ck](https://github.com/rustycl0ck), would you be willing to change configFiles to files and re-run awake?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/cisco-sso/charts/pull/7#issuecomment-406403109), or [mute the thread](https://github.com/notifications/unsubscribe-auth/ABPUlgLnm7j0JhGbu8ajmT0kRL6C_Si3ks5uIOsjgaJpZM4UQaiO).

2018-07-24 14:55 UTC, ghost approved these changes

2018-07-24 14:56 UTC, josdotso commented
@rustycl0ck  please self merge after awake and merge conflict fix.  I'm sorry dude!

2018-07-24 22:24 UTC, dcwangmit01 approved these changes
+1

2018-07-27 05:15 UTC, merged